# Generated by Django 5.0.2 on 2024-10-07 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_2', models.CharField(max_length=50)),
                ('field_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myApp.parent')),
            ],
        ),
    ]
